# Core
db:
  redis:
    emulate: true
    namespace: EG 

crypto:
  cipherKey: sensitiveKey
  algorithm: aes256
  saltRounds: 10

# OAuth2 Settings
session:
  secret: keyboard cat
  resave: false
  saveUninitialized: false
accessTokens:
  timeToExpiry: 7200000
refreshTokens:
  timeToExpiry: 7200000
authorizationCodes:
  timeToExpiry: 300000
plugins: 
  verify-token:
    package: "../../../plugins/verify-token/manifest.js"
  verifySelfAuth-token:
    package: "../../../plugins/verifySelfAuth-token/manifest.js" 
  verifyAdmin-token:
    package: "../../../plugins/verifyAdmin-token/manifest.js" 